spring:
  application:
    name: bigdata-segmentation-service
  datasource:
    username: dbuser
    password: '{cipher}b3bd7b4eeb38bf33b4dc2dec19d4ee0ba4154c4f0ed7c3554448e67c39bee8ab'
  # rabbitma 配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: '{cipher}c48b82b13e38331d252a659d35194cf00e8464cca6b64b64d3aae900613a619c'
  cloud:
    stream:
      binders:
        inventoryQ:
          destination: inventoryQ
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    service-url: 
      defaultZone: http://localhost:8760/eureka/
word:
  segmentation: N

#本配置文件中的路径的根目录，根目录+其他路径=绝对路径
#Windows用户请注意，路径分隔符统一使用/
root: /Volumes/Transcend/bigdata/hanlp-data
#核心词典路径
CoreDictionaryPath: data/dictionary/CoreNatureDictionary.txt
#2元语法词典路径
BiGramDictionaryPath: data/dictionary/CoreNatureDictionary.ngram.txt
#停用词词典路径
CoreStopWordDictionaryPath: data/dictionary/stopwords.txt
#同义词词典路径
CoreSynonymDictionaryDictionaryPath: data/dictionary/synonym/CoreSynonym.txt
#人名词典路径
PersonDictionaryPath: data/dictionary/person/nr.txt
#人名词典转移矩阵路径
PersonDictionaryTrPath: data/dictionary/person/nr.tr.txt
#繁简词典路径
TraditionalChineseDictionaryPath: data/dictionary/tc/TraditionalChinese.txt
#自定义词典路径，用;隔开多个自定义词典，空格开头表示在同一个目录，使用“文件名 词性”形式则表示这个词典的词性默认是该词性。优先级递减。
#另外data/dictionary/custom/CustomDictionary.txt是个高质量的词库，请不要删除
CustomDictionaryPath: data/dictionary/custom/CustomDictionary.txt; 现代汉语补充词库.txt; 全国地名大全.txt ns; 人名词典.txt; 机构名词典.txt; 上海地名.txt ns;data/dictionary/person/nrf.txt nrf

#CRF分词模型路径
CRFSegmentModelPath: data/model/segment/CRFSegmentModel.txt.bin
#HMM分词模型
HMMSegmentModelPath: data/model/segment/HMMSegmentModel.bin