spring:
  application:
    name: wordsegmentation-apigateway
zuul:
  routes:
    api-1:
      path: /user/**
      serviceId: wordsegmentation-service
    api-2:
      path: /club/**
      serviceId: wordsegmentation-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/